image: bradrydzewski/node:0.10
script:
  - apt-get install phantomjs
  - npm -g install grunt-cli karma bower
  - npm install
  - bower install
  - grunt build
  - grunt karma
notify:
  email:
    recipients:
      - golikov.aleksey@gmail.com
